name: Matrix

on:
  workflow_dispatch:

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read configuration.yaml
        id: read_configuration
        uses: mikefarah/yq@master
        with:
          cmd: yq eval 'keys' configuration.yaml -j
#      - name: Reuse a variable obtained in another step
#        run: echo "${{ steps.read_configuration.outputs.result }}"
    outputs:
      matrix: ${{ steps.read_configuration.outputs.result }}

  deploy:
    needs: read-config

    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.read-config.outputs.matrix) }}

    steps:
      - name: Echo Context
        run: echo "${{ matrix.package }}"