name: Matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read configuration.yaml
        id: read_configuration
        uses: mikefarah/yq@master
        with:
          cmd: yq '.' configuration.yaml
      - name: Reuse a variable obtained in another step
        run: echo ${{ steps.read_configuration.outputs.result }}
